
tomcat_install_dir=AUTO
tomcat_port_offset=AUTO

tomcat_url=https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.40/bin/apache-tomcat-10.1.40.zip
tomcat_checksum=4718ec31868afa756dd4d58746fce9d8532c57f9

tomcat_install_final_custom_script=mkdir -p ./conf/cmdbuild

#TODO java
include_embedded_java=false
java_url=https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz
java_checksum=b9517ecaa3c09b1eadf7b92fe6ad3036cbf8a551

#tomcat_config_overlay=database
#tomcat_config_overlay.database.file=./webapps/cmdbuild/WEB-INF/conf/database.conf
#tomcat_config_overlay.database.content=\n\n\
#db.password=postgres\n\
#db.url=jdbc:postgresql://localhost:5432/cmdbuild\n\
#db.username=postgres\n\n

