/*
 * CMDBuild has been developed and is managed by PAT srl
 You can use CMDBuild according to the license
 */
package org.cmdbuild.modeldiff.dms;

import jakarta.activation.DataHandler;
import java.util.Map;
import org.cmdbuild.dao.entrytype.Attribute;
import org.cmdbuild.modeldiff.core.CmSerializationHelper;
import static org.cmdbuild.modeldiff.core.CmSerializationHelper.ATTR_CARD_ATTACHMENT_CARD_ID_SERIALIZATION;
import static org.cmdbuild.modeldiff.core.CmSerializationHelper.ATTR_DESCRIPTION_SERIALIZATION;
import static org.cmdbuild.modeldiff.core.CmSerializationHelper.ATTR_DMS_DOCUMENT_AUTHOR_SERIALIZATION;
import org.cmdbuild.modeldiff.core.CmSerializationHelper.CardAttachmentSerializationHelper;
import org.cmdbuild.temp.TempService;
import static org.cmdbuild.utils.lang.CmConvertUtils.toLongOrNull;
import static org.cmdbuild.utils.lang.CmExceptionUtils.runtime;
import static org.cmdbuild.utils.lang.CmNullableUtils.isBlank;

/**
 * <b>Note</b>: <code>dataHandler</code> is <code>null</code> if this handle refers 
 * to a document already persisted in <i>DMS</i>.
 * 
 * @author afelice
 */
public class DocumentHandle {

    private final String documentId;
    private final DataHandler dataHandler;
    private final String filename;
    private final Map<String, Object> metadata;

    // Optional parameters
    private final String description;
    private final String author;

    /**
     * 
     * @param documentId in <i><code>FILE</code> {@link Attribute}s</i>, is generated by
     * {@link TempService}.
     * @param metadata
     * @param dataHandler 
     */
    public DocumentHandle(String documentId, Map<String, Object> metadata, DataHandler dataHandler) {
        this.documentId = documentId;
        this.dataHandler = dataHandler;
        this.filename = CardAttachmentSerializationHelper.getFileName(metadata);

        // May be unchanged, so not present in given metadata
        this.description = CardAttachmentSerializationHelper.getDescription(metadata);
        this.author = CardAttachmentSerializationHelper.getAuthor(metadata);
        this.metadata = metadata;
    }

    @Override
    public String toString() {
        return "DocumentHandle{documentId=< %s >,filename=< %s >,description=< %s >}".formatted(documentId, filename, description);
    }

    public String getDocumentId() {
        return documentId;
    }

    public String getFilename() {
        return filename;
    }

    public String getAuthor() {
        return author;
    }

    public boolean hasAuthor() {
        return metadata.containsKey(ATTR_DMS_DOCUMENT_AUTHOR_SERIALIZATION);
    }

    public String getDescription() {
        return description;
    }

    public boolean hasDescription() {
        return metadata.containsKey(ATTR_DESCRIPTION_SERIALIZATION);
    }

    public long getCardMetadataId() {
        return toLongOrNull(metadata.get(ATTR_CARD_ATTACHMENT_CARD_ID_SERIALIZATION));
    }
    
    /**
     * if set in <code>metadata</code> while updating a <i>DMS document</i>, CMDBuld
     * will update the updated document <code>version</code> to a new <i>major</i>, for example, 
     * from <code>1.2</code> to <code>2.0</code>.
     * @return 
     */
    public boolean hasMajorVersionFlag() {
        return Boolean.TRUE.equals(metadata.get(CmSerializationHelper.ATTR_DMS_DOCUMEMT_MAJOR_VERSION_FLAG_SERIALIZATION));
    }
    
    public DataHandler getDataHandler() {
        return dataHandler;
    }

    public Map<String, Object> getMetadata() {
        return metadata;
    }
    
    public Long getCategoryId() {
        return toLongOrNull(metadata.get(CmSerializationHelper.ATTR_DMS_DOCUMENT_CATEGORY_ID_SERIALIZATION));
    }

    private void checkExistence(String propName, Object foundValue) {
        if (foundValue == null) {
            throw runtime("error deserializing document metadata, couldn't find =< %s > property".formatted(propName));
        }
        if (isBlank(foundValue) || !(foundValue instanceof String)) {
            throw runtime("error deserializing document metadata, value for =< %s > property expected a string, found =< %s >".formatted(propName, foundValue));
        }
    }
    
}
