/*
 * CMDBuild has been developed and is managed by PAT srl
 * You can use CMDBuild according to the license
 */
package org.cmdbuild.modeldiff.dms;

import java.util.Map;
import org.cmdbuild.dao.beans.Card;
import org.cmdbuild.modeldiff.core.CmSerializationHelper;
import org.cmdbuild.utils.json.CmJsonUtils;
import static org.cmdbuild.utils.json.CmJsonUtils.fromJson;
import static org.cmdbuild.utils.lang.CmNullableUtils.isBlank;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 * @author afelice
 */
public class DocumentHandleTest {

    /**
     * <i>{@link Card} attachment</i> serialization with unset <i>description</i>.
     * 
     * <p><ul>
     * <li><code>"description"</code> and <code>"Description</code> are both
     * generated by current CMDBuild serialization;
     * <li>UI sets only <code>"Description"</code> when changing it.
     * </ul>
     */
    private static final String A_KNOWN_OLD_CARD_ATTACHMENT_SERIALIZATION = """
    {
        "category": 92857368,
        "Category": "92857368",
        "_category": 92857368,
        "_category_name": "IMMAGINI_ISPEZIONI",
        "_category_description": "Immagine ispezione",
        "_category_description_translation": "Immagine ispezione",
        "_can_update": true,
        "_can_delete": true,
        "name": "Screenshot_20250507-155057.CMDBuild.png",
        "description": "",
        "Description": null,
        "version": "1.0",
        "author": "admin",
        "created": "2026-01-30T11:56:24.126Z",
        "modified": "2026-01-30T11:56:24.461Z",
        "_author_description": "Administrator",
        "_id": "awqcgsba1d1uwwnzxlqwwphc9urjgnv44mpcyt81z97n2ukwflo1ij3gsp1c2p",
        "_card": 93823858,
        "Code": "123456789",
        "Notes": null,
        "IDOpera": "A24_119sx",
        "NomeConvenzionale": "Galleria Torrione 2° Sx",
        "DataDocumento": "2026-01-30T11:54:57.923Z",
        "TrattaRiferimento": "L'AQUILA OVEST - L'AQUILA EST",
        "TroncoAppartenenza": "A24T2",
        "CSA": "Centro di Esercizio 3 AQ A24",
        "NomeInfrastruttura": "A24",
        "IDIspezione": "TI.2025.0008",
        "TipoIspezione": "Straordinaria",
        "IDComponente": "A24_119sx_CI-1",
        "CodiceDifetto": "1.1",
        "MimeType": "image/png",
        "Id": 93823858,
        "IdClass": "DmsTunnelInspectionImage",
        "IdTenant": null,
        "FileName": "Screenshot_20250507-155057.CMDBuild.png",
        "Hash": "unknown",
        "Size": 66692,
        "CreationDate": "2026-01-30T11:56:24.126Z"
    }                                                                            
    """;
    
    /**
     * <i>{@link Card} attachment</i> serialization with <b>set</b> <i>description</i>.
     * 
     * <p><ul>
     * <li><code>"description"</code> and <code>"Description</code> are both
     * generated by current CMDBuild serialization;
     * <li>UI sets only <code>"Description"</code> when changing it.
     * </ul>
     */    
    private static final String A_KNOWN_MODIFIED_CARD_ATTACHMENT_SERIALIZATION = """
    {
        "_id": "awqcgsba1d1uwwnzxlqwwphc9urjgnv44mpcyt81z97n2ukwflo1ij3gsp1c2p",
        "majorVersion": false,
        "_category_name": "IMMAGINI_ISPEZIONI",
        "_category_description": "Immagine ispezione",
        "_category_description_translation": "Immagine ispezione",
        "MimeType": "image/png",
        "Card": null,
        "DocumentId": null,
        "FileName": "Screenshot_20250507-154845.CMDBuild.png",
        "Version": null,
        "Category": "92857368",
        "Hash": "unknown",
        "Size": 66692,
        "CreationDate": "2026-01-30T11:56:24.126Z",
        "Code": "1234",
        "Description": "Numeri",
        "IDOpera": "A24_119sx",
        "NomeConvenzionale": "Galleria Torrione 2° Sx",
        "DataDocumento": "2026-01-30T12:03:22.965Z",
        "TrattaRiferimento": "L'AQUILA OVEST - L'AQUILA EST",
        "TroncoAppartenenza": "A24T2",
        "CSA": "Centro di Esercizio 3 AQ A24",
        "NomeInfrastruttura": "A24",
        "IDIspezione": "TI.2025.0008",
        "TipoIspezione": "Straordinaria",
        "IDComponente": "A24_119sx_CI-1",
        "CodiceDifetto": "1.2",
        "category": 92857368,
        "_category": 92857368,
        "_can_update": true,
        "_can_delete": true,
        "name": "Screenshot_20250507-154845.CMDBuild.png",
        "description": "",
        "version": "1.1",
        "author": "admin",
        "created": "2026-01-30T11:56:24.126Z",
        "modified": "2026-01-30T11:56:24.461Z",
        "_author_description": "Administrator",
        "_card": 93823858,
        "Notes": null,
        "Id": 93823858,
        "IdClass": "DmsTunnelInspectionImage",
        "IdTenant": null
    }
    """ ;

    /**
     * <i>{@link Card} attachment</i> serialization with <b>set</b> <i>description</i>.
     * 
     * <p><ul>
     * <li><code>"FileName"</code> and <code>"Description"</code> are set by UI.
     * <li><code>"_id"</code> is a <i>UUID</i>;
     * .
     * </ul>
     */    
    private static final String A_KNOWN_NEW_CARD_ATTACHMENT_SERIALIZATION = """
    {
        "_id": "f298c94c-31a1-4174-93cf-59f6c174e334",
        "majorVersion": false,
        "_category_name": "IMMAGINI_ISPEZIONI",
        "_category_description": "Immagine ispezione",
        "_category_description_translation": "Immagine ispezione",
        "MimeType": "image/png",
        "Card": null,
        "DocumentId": null,
        "FileName": "NEW_Screenshot_20250507-154845.CMDBuild.png",
        "Version": null,
        "Category": "92857368",
        "Hash": "unknown",
        "Size": 66692,
        "CreationDate": "2026-01-30T11:56:24.126Z",
        "Code": "1234",
        "Description": "NEW_Numeri",
        "IDOpera": "A24_119sx",
        "NomeConvenzionale": "Galleria Torrione 2° Sx",
        "DataDocumento": "2026-01-30T12:03:22.965Z",
        "TrattaRiferimento": "L'AQUILA OVEST - L'AQUILA EST",
        "TroncoAppartenenza": "A24T2",
        "CSA": "Centro di Esercizio 3 AQ A24",
        "NomeInfrastruttura": "A24",
        "IDIspezione": "TI.2025.0008",
        "TipoIspezione": "Straordinaria",
        "IDComponente": "A24_119sx_CI-1",
        "CodiceDifetto": "1.2",
        "category": 92857368,
        "_category": 92857368,
        "_can_update": true,
        "_can_delete": true,
        "name": "Screenshot_20250507-154845.CMDBuild.png",
        "description": "",
        "version": "1.1",
        "author": "admin",
        "created": "2026-01-30T11:56:24.126Z",
        "modified": "2026-01-30T11:56:24.461Z",
        "_author_description": "Administrator",
        "_card": 93823858,
        "Notes": null,
        "Id": 93823858,
        "IdClass": "DmsTunnelInspectionImage",
        "IdTenant": null
    }                                                                            
    """;
    
    /**
     * Test of toString method, of class DocumentHandle.
     * 
     * <p>In current CMDBuild <i>card attachment</i> serialization, if <i>description</i> not set
     * <ul>
     * <li><code>"description"</code> is <code>""</code>;
     * <li><code>"Description"</code> is <code>null</code>.
     * </ul>
     */
    @Test
    public void testDescription_Empty() {
        System.out.println("description_Empty");
        
        //arrange:
        Map<String, Object> cardAttachmentSerialization = fromJson(A_KNOWN_OLD_CARD_ATTACHMENT_SERIALIZATION, CmJsonUtils.MAP_OF_OBJECTS);
        String documentId = CmSerializationHelper.get(cardAttachmentSerialization, String.class, CmSerializationHelper.ATTR_ID_SERIALIZATION);
                
        //act:
        DocumentHandle result = new DocumentHandle(documentId, cardAttachmentSerialization, null);
        
        //assert:
        assertTrue(isBlank(result.getDescription()));
        assertEquals("awqcgsba1d1uwwnzxlqwwphc9urjgnv44mpcyt81z97n2ukwflo1ij3gsp1c2p", result.getDocumentId());
        assertFalse(CmSerializationHelper.isUUID(result.getDocumentId()));
        assertEquals("admin", result.getAuthor());
    }

    /**
     * Test of toString method, of class DocumentHandle.
     * 
     * <p><ul>
     * <li><code>"description"</code> and <code>"Description"</code> are both
     * generated by current CMDBuild serialization;
     * <li>UI sets only <code>"Description"</code> when changing it.
     * </ul>
     */
    @Test
    public void testDescription_ChangedByUI() {
        System.out.println("description_ChangedByUI");
        
        //arrange:
        Map<String, Object> cardAttachmentSerialization = fromJson(A_KNOWN_MODIFIED_CARD_ATTACHMENT_SERIALIZATION, CmJsonUtils.MAP_OF_OBJECTS);
        String documentId = CmSerializationHelper.get(cardAttachmentSerialization, String.class, CmSerializationHelper.ATTR_ID_SERIALIZATION);
                
        //act:
        DocumentHandle result = new DocumentHandle(documentId, cardAttachmentSerialization, null);
        
        //assert:
        assertEquals("Numeri", result.getDescription());
        assertEquals("awqcgsba1d1uwwnzxlqwwphc9urjgnv44mpcyt81z97n2ukwflo1ij3gsp1c2p", result.getDocumentId());
        assertFalse(CmSerializationHelper.isUUID(result.getDocumentId()));
        assertEquals("admin", result.getAuthor());
    }    
    
    /**
     * Test of class DocumentHandle, new file.
     * 
     * <p><ul>
     * <li><code>"description"</code> and <code>"Description"</code> are both
     * generated by current CMDBuild serialization;
     * <li>UI sets only <code>"Description"</code> when changing it.
     * </ul>
     */
    @Test
    public void testDescription_NewFileByUI() {
        System.out.println("description_NewFileByUI");
        
        //arrange:
        Map<String, Object> cardAttachmentSerialization = fromJson(A_KNOWN_NEW_CARD_ATTACHMENT_SERIALIZATION, CmJsonUtils.MAP_OF_OBJECTS);
        String documentId = CmSerializationHelper.get(cardAttachmentSerialization, String.class, CmSerializationHelper.ATTR_ID_SERIALIZATION);
                
        //act:
        DocumentHandle result = new DocumentHandle(documentId, cardAttachmentSerialization, null);
        
        //assert:
        assertEquals("NEW_Numeri", result.getDescription());
        assertEquals("f298c94c-31a1-4174-93cf-59f6c174e334", result.getDocumentId());
        assertTrue(CmSerializationHelper.isUUID(result.getDocumentId()));
        assertEquals("NEW_Screenshot_20250507-154845.CMDBuild.png", result.getFilename());
        assertEquals("admin", result.getAuthor());
    }
    
}
